# Generated by Django 4.2.3 on 2023-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
