# Generated by Django 4.2.3 on 2023-07-26 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='name',
            field=models.CharField(default='testname', max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserGuildConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
