# Generated by Django 4.2.3 on 2023-09-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0006_alter_user_display_name_guildcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildcode',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='TestyBooby', max_length=30, null=True),
        ),
    ]
