# Generated by Django 4.2.3 on 2023-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0007_guildcode_created_by_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='RightGuineafowl', max_length=30, null=True),
        ),
    ]
