# Generated by Django 4.2.3 on 2023-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0010_rename_guildrostercharacter_guildcharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildcharacter',
            name='character_class',
            field=models.CharField(choices=[('warlock', 'Warlock'), ('mage', 'Mage'), ('rogue', 'Rogue'), ('warrior', 'Warrior'), ('priest', 'Priest'), ('druid', 'Druid'), ('hunter', 'Hunter'), ('shaman', 'Shaman'), ('paladin', 'Paladin'), ('death_knight', 'Death Knight'), ('monk', 'Monk'), ('demon_hunter', 'Demon Hunter'), ('evoker', 'Evoker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guildcharacter',
            name='role',
            field=models.CharField(choices=[('tank', 'Tank'), ('healer', 'Healer'), ('melee', 'Melee DPS'), ('ranged', 'Ranged DPS')], max_length=60),
        ),
        migrations.AlterField(
            model_name='guildcharacter',
            name='spec',
            field=models.CharField(choices=[('affliction', 'Affliction'), ('demonology', 'Demonology'), ('destruction', 'Destruction'), ('arcane', 'Arcane'), ('fire', 'Fire'), ('frost', 'Frost'), ('assassination', 'Assassination'), ('outlaw', 'Outlaw'), ('subtlety', 'Subtlety'), ('arms', 'Arms'), ('fury', 'Fury'), ('protection', 'Protection'), ('discipline', 'Discipline'), ('holy', 'Holy'), ('shadow', 'Shadow'), ('balance', 'Balance'), ('feral', 'Feral'), ('guardian', 'Guardian'), ('restoration', 'Restoration'), ('beast_mastery', 'Beast Mastery'), ('marksmanship', 'Marksmanship'), ('survival', 'Survival'), ('elemental', 'Elemental'), ('enhancement', 'Enhancement'), ('retribution', 'Retribution'), ('blood', 'Blood'), ('unholy', 'Unholy'), ('brewmaster', 'Brewmaster'), ('mistweaver', 'Mistweaver'), ('windwalker', 'Windwalker'), ('havoc', 'Havoc'), ('vengeance', 'Vengeance')], max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='AbsoluteRodent', max_length=30, null=True),
        ),
    ]
