# Generated by Django 4.2.3 on 2023-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0014_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='guildcharacter',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='guildcharacter',
            name='role',
            field=models.CharField(choices=[('tank', 'Tank'), ('healer', 'Healer'), ('melee', 'Melee DPS'), ('ranged', 'Ranged DPS')], max_length=16),
        ),
        migrations.AlterField(
            model_name='guildcharacter',
            name='spec',
            field=models.CharField(choices=[('affliction', 'Affliction'), ('demonology', 'Demonology'), ('destruction', 'Destruction'), ('arcane', 'Arcane'), ('fire', 'Fire'), ('frost', 'Frost'), ('assassination', 'Assassination'), ('outlaw', 'Outlaw'), ('subtlety', 'Subtlety'), ('arms', 'Arms'), ('fury', 'Fury'), ('protection', 'Protection'), ('discipline', 'Discipline'), ('holy', 'Holy'), ('shadow', 'Shadow'), ('balance', 'Balance'), ('feral', 'Feral'), ('guardian', 'Guardian'), ('restoration', 'Restoration'), ('beast_mastery', 'Beast Mastery'), ('marksmanship', 'Marksmanship'), ('survival', 'Survival'), ('elemental', 'Elemental'), ('enhancement', 'Enhancement'), ('retribution', 'Retribution'), ('blood', 'Blood'), ('unholy', 'Unholy'), ('brewmaster', 'Brewmaster'), ('mistweaver', 'Mistweaver'), ('windwalker', 'Windwalker'), ('havoc', 'Havoc'), ('vengeance', 'Vengeance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
