# Generated by Django 4.2.3 on 2023-09-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0015_alter_guild_name_alter_guildcharacter_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
