# Generated by Django 4.2.3 on 2023-09-25 14:06

from django.db import migrations, models
import guilds.models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0018_alter_guildcharacter_character_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='id',
            field=models.CharField(default=guilds.models.get_smaller_uuid, editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
