# Generated by Django 4.2.3 on 2023-09-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0019_alter_guild_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_id', models.IntegerField(db_index=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
            ],
        ),
        migrations.CreateModel(
            name='BossRosterCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in', 'In'), ('bench', 'Bench')], max_length=16)),
                ('boss_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.bossroster')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guildcharacter')),
            ],
        ),
    ]
