# Generated by Django 4.2.3 on 2023-09-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0020_bossroster_bossrostercharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossroster',
            name='characters',
            field=models.ManyToManyField(blank=True, to='guilds.guildcharacter'),
        ),
        migrations.AlterField(
            model_name='bossroster',
            name='boss_id',
            field=models.IntegerField(choices=[('1', 'Kazzara'), ('2', 'Assault'), ('3', 'Amalgamation'), ('4', 'Experiments'), ('5', 'Rashok'), ('6', 'Zskarn'), ('7', 'Magmorax'), ('8', 'Neltharion'), ('9', 'Sarkareth')]),
        ),
        migrations.DeleteModel(
            name='BossRosterCharacter',
        ),
    ]
