# Generated by Django 4.2.3 on 2023-09-26 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0021_bossroster_characters_alter_bossroster_boss_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossroster',
            name='boss_id',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
    ]
