# Generated by Django 4.2.3 on 2023-09-28 13:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0022_alter_bossroster_boss_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bossroster',
            name='characters',
            field=models.ManyToManyField(to='guilds.guildcharacter'),
        ),
        migrations.CreateModel(
            name='BossPlanRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.IntegerField(validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(0)])),
                ('spell_name', models.CharField(max_length=50)),
                ('spell_id', models.IntegerField()),
                ('spell_link', models.CharField(blank=True, max_length=200, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('event_type', models.CharField(choices=[('SPELL_CAST_SUCCESS', 'Scc'), ('SPELL_CAST_START', 'Scs'), ('SPELL_AURA_APPLIED', 'Saa'), ('SPELL_AURA_REMOVED', 'Sar')], max_length=20)),
                ('order', models.IntegerField(default=999)),
                ('BossPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.bossplan')),
            ],
        ),
        migrations.AddField(
            model_name='bossplan',
            name='boss_roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.bossroster'),
        ),
        migrations.CreateModel(
            name='AssignedCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_instruction', models.CharField(blank=True, max_length=60, null=True)),
                ('spell_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=999)),
                ('for_everyone', models.BooleanField(default=False)),
                ('BossPlanRow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.bossplanrow')),
                ('GuildCharacter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guilds.guildcharacter')),
            ],
        ),
    ]
