# Generated by Django 4.2.3 on 2023-09-29 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0023_bossplan_alter_bossroster_characters_bossplanrow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcooldown',
            old_name='order',
            new_name='column',
        ),
        migrations.RemoveField(
            model_name='bossplan',
            name='boss_roster',
        ),
        migrations.AddField(
            model_name='bossplan',
            name='boss_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='bossplan',
            name='difficulty',
            field=models.CharField(choices=[('heroic', 'Heroic'), ('mythic', 'Mythic')], default='mythic', max_length=20),
        ),
        migrations.AddField(
            model_name='bossplan',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guilds.guild'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bossplan',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
