# Generated by Django 4.2.3 on 2023-10-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0024_rename_order_assignedcooldown_column_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bossplanrow',
            old_name='BossPlan',
            new_name='boss_plan',
        ),
    ]
