# Generated by Django 4.2.3 on 2023-10-01 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0025_rename_bossplan_bossplanrow_boss_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossplanrow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
