# Generated by Django 4.2.3 on 2023-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0026_alter_bossplanrow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossplanrow',
            name='spell_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bossplanrow',
            name='spell_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
