# Generated by Django 4.2.3 on 2023-10-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0027_alter_bossplanrow_spell_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossplanrow',
            name='event_type',
            field=models.CharField(blank=True, choices=[('SPELL_CAST_SUCCESS', 'Scc'), ('SPELL_CAST_START', 'Scs'), ('SPELL_AURA_APPLIED', 'Saa'), ('SPELL_AURA_REMOVED', 'Sar')], max_length=20, null=True),
        ),
    ]
