# Generated by Django 4.2.3 on 2023-10-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0028_alter_bossplanrow_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcooldown',
            old_name='BossPlanRow',
            new_name='boss_plan_row',
        ),
        migrations.RenameField(
            model_name='assignedcooldown',
            old_name='GuildCharacter',
            new_name='character',
        ),
        migrations.AlterField(
            model_name='assignedcooldown',
            name='column',
            field=models.IntegerField(default=0),
        ),
    ]
