# Generated by Django 4.2.3 on 2023-10-01 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0029_rename_bossplanrow_assignedcooldown_boss_plan_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossplanrow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
